Fix invalid handle scope error when Dart_IsClosure is used.
dart/runtime/vm/handles_impl.h:98: error: expected: isolate->top_handle_scope() != NULL

R=srdjan@google.com

Review URL: https://codereview.chromium.org//416663003

git-svn-id: https://dart.googlecode.com/svn/branches/bleeding_edge@38520 260f80e4-7a28-3924-810f-c04153c831b5