Update dartc test expectations.
Fix bug in test that assumes NoSuchMethodError is an Exception.

TBR=johnniwinter@google.com

Review URL: https://chromiumcodereview.appspot.com//10910192

git-svn-id: https://dart.googlecode.com/svn/branches/bleeding_edge@12176 260f80e4-7a28-3924-810f-c04153c831b5