Remove references to ObjectNotClosureException and ClosureArgumentMismatchException from the VM (issue 6124). These are replaced with NoSuchMethodError for now (work in progress). Review URL: https://codereview.chromium.org//11312019
git-svn-id: https://dart.googlecode.com/svn/branches/bleeding_edge@14362 260f80e4-7a28-3924-810f-c04153c831b5