Fix failure   ../runtime/vm/object.cc:7149: error: unimplemented code   Abort in standalone tests when run with 64bit dart.
The ioctl function when used with FIONREAD was being passed a 64 bit
argument which is incorrect.

Documentation on ioctl:
FIONREAD
The FIONREAD ioctl returns the number of data bytes (in all data
messages queued) in the location pointed to by the arg parameter. The
ioctl returns a 32-bit quantity for both 32-bit and 64-bit
application., Therefore, code that passes the address of a long
variable needs to be changed to pass an int variable for 64–bit
applications.
Review URL: http://codereview.chromium.org//9194002

git-svn-id: https://dart.googlecode.com/svn/branches/bleeding_edge@3250 260f80e4-7a28-3924-810f-c04153c831b5