Fix clang unused-private-field error.
../../runtime/vm/dart_api_state.h:736:18: error: private field 'key_' is not used [-Werror,-Wunused-private-field]
  ThreadLocalKey key_;
                   ^
R=scheglov@google.com
TEST=ninja -C out/Debug
Signed-off-by: Thiago Farina <tfarina@chromium.org>

Review URL: https://codereview.chromium.org//14189023

Patch from Thiago Farina <tfarina@chromium.org>.

git-svn-id: https://dart.googlecode.com/svn/branches/bleeding_edge@21778 260f80e4-7a28-3924-810f-c04153c831b5